# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2

nodes = %w[ spine01 spine02
            leaf01 leaf02
            leaf03 leaf04 ]

nodes.each do |node|
  vagrantfile = "./Vagrantfile.#{node}"
  load File.expand_path(vagrantfile) if File.exists?(vagrantfile)
end

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|

    ansible.groups = {
    "vqfx10k"      => ["spine1", "spine2", "leaf1", "leaf2", "leaf3" ],
    "spine"        => ["spine1", "spine2"],
    "leaf"         => ["leaf1", "leaf2", "leaf3" ],
    "server"       => ["srv1", "srv2", "srv3" ],
    "all:children" => ["vqfx10k", "server" ]
    }

    ansible.playbook = "playbook.yml"
  end
end
