- name: Generate and Deploy Configuration
  hosts: juniper
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: "gather_facts: junos"
      junos_facts:

    - name: "Build configuration"
      template:
        src: vqfx.conf.j2
        dest: "{{ junos_conf_file_path }}"

    - name: "Deploy config to device"
      junos_config:
        backup: yes
        src: "{{ junos_conf_file_path }}"
        update: override
