# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2
nodes = %w[ tower server01
            server02 ]

nodes.each do |node|
  vagrantfile = "./Vagrantfile.#{node}"
  load File.expand_path(vagrantfile) if File.exists?(vagrantfile)
end

Vagrant.configure("2") do |config|
  config.vm.provision "ansible" do |ansible|

    ansible.groups = {
      "ansible"      => ["tower", "server01", "server02" ],
      "tower"        => ["tower"],
      "server"       => ["server01", "server02" ],
      "node"         => ["server01", "server02" ]
    }

    ansible.playbook = "../deploy.yml"
  end
end
